-- Migration 040: commission tracking.
--
-- Three kinds of commission are auto-generated by a trigger on
-- jobs:
--   1. reception_visit ($40)  — fires when a receptionist's lead
--                               progresses past New Lead (the
--                               salesperson actually went on the
--                               visit, signalled by either the
--                               questionnaire being filled or the
--                               card moving to estimate_draft+).
--   2. sales_signed   (6% of estimate total) — fires when the lead
--                               reaches contract_signed / in_progress
--                               / completed; recipient is whoever
--                               assigned_to points at, IF that user
--                               has role='sales'.
--   3. reception_signed ($300) — same trigger as sales_signed, but
--                               paid to the receptionist who owned
--                               the lead.
--
-- Everything is idempotent via the (job_id, kind, recipient_name)
-- unique constraint + ON CONFLICT DO NOTHING. A reassignment of
-- assigned_to AFTER the row was already created does NOT generate
-- a duplicate — the original recipient keeps the commission. That
-- matches the real-world rule "whoever closed it gets paid".
--
-- Brenda / Inácio / Admin can override `amount` and `percent` in
-- the UI to handle one-off bonuses or adjustments. The trigger
-- only INSERTS — it never UPDATES existing rows — so manual edits
-- survive subsequent pipeline_status changes.

CREATE TABLE IF NOT EXISTS public.commissions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id          uuid NOT NULL REFERENCES public.jobs(id) ON DELETE CASCADE,
  kind            text NOT NULL CHECK (kind IN ('sales_signed','reception_visit','reception_signed')),
  recipient_name  text NOT NULL,
  recipient_role  text,
  trigger_at      timestamptz NOT NULL DEFAULT now(),
  base_amount     numeric,
  percent         numeric,
  amount          numeric NOT NULL DEFAULT 0,
  paid            boolean NOT NULL DEFAULT false,
  paid_at         timestamptz,
  paid_by         text,
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (job_id, kind, recipient_name)
);

CREATE INDEX IF NOT EXISTS commissions_recipient_idx
  ON public.commissions (recipient_name, recipient_role);
CREATE INDEX IF NOT EXISTS commissions_job_idx
  ON public.commissions (job_id);
CREATE INDEX IF NOT EXISTS commissions_paid_idx
  ON public.commissions (paid)
  WHERE paid = false;

ALTER TABLE public.commissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS commissions_anon_all ON public.commissions;
CREATE POLICY commissions_anon_all
  ON public.commissions
  FOR ALL
  TO anon, authenticated
  USING (true)
  WITH CHECK (true);

-- ─── Auto-generation trigger ─────────────────────────────────────

CREATE OR REPLACE FUNCTION public.jobs_generate_commissions()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_owner_role     text;
  v_assignee_role  text;
  v_estimate_total numeric;
  v_visit_done     boolean;
  v_signed_done    boolean;
BEGIN
  -- "Visit happened" predicate — receptionist earns $40.
  v_visit_done := (
       NEW.answers IS NOT NULL
    OR (NEW.pipeline_status IS NOT NULL
        AND NEW.pipeline_status NOT IN ('new_lead'))
  );

  -- "Contract signed" predicate — salesperson earns 6%, receptionist earns $300.
  v_signed_done := (
    NEW.pipeline_status IN ('contract_signed', 'in_progress', 'completed')
  );

  -- ─── 1. Receptionist VISIT commission ($40) ───────────────────
  IF v_visit_done AND NEW.lead_owner IS NOT NULL THEN
    SELECT role INTO v_owner_role
      FROM public.users
     WHERE name = NEW.lead_owner
     LIMIT 1;

    IF v_owner_role = 'receptionist' THEN
      INSERT INTO public.commissions
        (job_id, kind, recipient_name, recipient_role, amount)
      VALUES
        (NEW.id, 'reception_visit', NEW.lead_owner, 'receptionist', 40)
      ON CONFLICT (job_id, kind, recipient_name) DO NOTHING;
    END IF;
  END IF;

  -- ─── 2. Contract signed commissions ───────────────────────────
  IF v_signed_done THEN
    -- 2a. Sales (6% of latest estimate total) for assigned salesperson
    IF NEW.assigned_to IS NOT NULL THEN
      SELECT role INTO v_assignee_role
        FROM public.users
       WHERE name = NEW.assigned_to
       LIMIT 1;

      IF v_assignee_role = 'sales' THEN
        SELECT total_amount INTO v_estimate_total
          FROM public.estimates
         WHERE job_id = NEW.id
         ORDER BY created_at DESC
         LIMIT 1;

        INSERT INTO public.commissions
          (job_id, kind, recipient_name, recipient_role, base_amount, percent, amount)
        VALUES
          (NEW.id, 'sales_signed', NEW.assigned_to, 'sales',
           COALESCE(v_estimate_total, 0), 6,
           COALESCE(v_estimate_total, 0) * 0.06)
        ON CONFLICT (job_id, kind, recipient_name) DO NOTHING;
      END IF;
    END IF;

    -- 2b. Receptionist signed bonus ($300)
    IF NEW.lead_owner IS NOT NULL THEN
      SELECT role INTO v_owner_role
        FROM public.users
       WHERE name = NEW.lead_owner
       LIMIT 1;

      IF v_owner_role = 'receptionist' THEN
        INSERT INTO public.commissions
          (job_id, kind, recipient_name, recipient_role, amount)
        VALUES
          (NEW.id, 'reception_signed', NEW.lead_owner, 'receptionist', 300)
        ON CONFLICT (job_id, kind, recipient_name) DO NOTHING;
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS jobs_generate_commissions_trg ON public.jobs;
CREATE TRIGGER jobs_generate_commissions_trg
  AFTER INSERT OR UPDATE ON public.jobs
  FOR EACH ROW
  EXECUTE FUNCTION public.jobs_generate_commissions();

-- ─── Keep updated_at fresh on commissions edits ──────────────────
CREATE OR REPLACE FUNCTION public.commissions_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS commissions_touch_updated_at_trg ON public.commissions;
CREATE TRIGGER commissions_touch_updated_at_trg
  BEFORE UPDATE ON public.commissions
  FOR EACH ROW
  EXECUTE FUNCTION public.commissions_touch_updated_at();
